### ISSUE TITLE
Проблема с ДБ 

### ISSUE THREAD

**Issue by AleksandrNagovitsyn** [AleksandrNagovitsyn/TXTSearch#1]
@coursar  У меня вот такой лог выходит, при запуске сервера 
![изображение](https://user-images.githubusercontent.com/55318485/70441609-c11c3a00-1aa5-11ea-8935-8cac6612f409.png)
Ведет на этот метод, строка 56 
https://github.com/AleksandrNagovitsyn/TXTSearch/blob/2d77b351b4965b577d079a9429a7a597fb2ba25f/src/main/java/ru/itpark/repository/RepositoryJdbcImpl.java#L54-L61

Пробовал напрямую вызвать этот метод 
https://github.com/AleksandrNagovitsyn/TXTSearch/blob/2d77b351b4965b577d079a9429a7a597fb2ba25f/src/main/java/ru/itpark/repository/RepositoryJdbcImpl.java#L64

Такой же exception, только ведет в jdbctemplate. Я так понимаю, у меня где-то ошибка в подключении к БД?

**Comment by coursar** [comment]
У вас `text.getId()` равен `null`. Поэтому вы получаете NPE. Используйте `text.getId() == null`

**Comment by AleksandrNagovitsyn** [comment]
@coursar Изменил, теперь такой лог 
![изображение](https://user-images.githubusercontent.com/55318485/70512240-d6927200-1b40-11ea-93d7-3e5fee1c034b.png)
Ведет в эту библиотеку https://github.com/AleksandrNagovitsyn/JDBCTemplate/blob/master/src/main/java/util/JdbcTemplate.java
сюда https://github.com/AleksandrNagovitsyn/JDBCTemplate/blob/19cb2920d43df2d8649969e8ae2cb7b4c4b52e48/src/main/java/util/JdbcTemplate.java#L48

Я продебажил, в общем DataSource у меня null, в этой строке https://github.com/AleksandrNagovitsyn/TXTSearch/blob/2d77b351b4965b577d079a9429a7a597fb2ba25f/src/main/java/ru/itpark/servlet/FrontServlet.java#L37

Может драйверов каких-то не хватает ? Я так понимаю, датасоурс не может найти путь к подключению, при том, что код индентичен вашему 

p.s. Вы еще говорили ,что нужно конфиг настраивать для дебага и какую-то переменную создать, а какую не напомните? У меня просто вроде без этого все дебажит
