### ISSUE TITLE
Не работает на разных устройствах 

### ISSUE THREAD

**Issue by AleksandrNagovitsyn** [AleksandrNagovitsyn/TXTSearch#2]
На одном ПК сервис работает, на другом нет: 

![image](https://user-images.githubusercontent.com/55318485/71019762-ff4fd400-210b-11ea-91e8-08c6e18011e8.png)

**Comment by coursar** [comment]
На каком конкретно не работает? Версия ОС, разрядность, Java, Tomcat.

**Comment by AleksandrNagovitsyn** [comment]
Windows 10, 64 бит java 11, Tomcat 9.0.29  у обоих ПК 

Я сейчас проверил, это скорее всего связано с JDBCTemplate https://github.com/AleksandrNagovitsyn/JDBCTemplate. 

Потому что, в трэвисе вот такой лог 
![image](https://user-images.githubusercontent.com/55318485/71024472-109dde00-2116-11ea-9c7f-176d7a333349.png)

Когда деплою JDBCTemplate в консоли выходит такое сообщение (в одну строку):
 Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.7:deploy (default-deploy) on project jdbctemplate: Failed to deploy artifacts: Could not transfer artifact ru.itpark:jdbctemplate:jar:1.0 from/to github (https://maven.pkg.github.com/AleksandrNagovitsyn/JDBCTemplate/): Failed to transfer file https://maven.pkg.github.com/AleksandrNagovitsyn/JDBCTemplate/ru/itpark/jdbctemplate/1.0/jdbctemplate-1.0.jar with status code 422


Видео несколько раз пересмотрел, перепроверил. Токен в settings.xml на обоих ПК прописан

**Comment by coursar** [comment]
Вам нужно:
1. Закинуть модуль jdbctemplate в текущий проект (в противном случае придётся settings.xml закидывать и на тревис и на хероку)
2. Переименовать его, например, в jdbc-template (т.к. в рамках вашего Github аккаунта не может быть двух одинаковых артифактов)

**Comment by AleksandrNagovitsyn** [comment]
@coursar 
Получается надо создать папку в основном проекте, скопировать туда классы JDBCTemplate и прописать module в pom.xml ? А зачем тогда вообще запаковывать JDBCTemplate и создавать для него репозиторий, если придется его так постоянно копировать?

**Comment by coursar** [comment]
Да, отдельный не нужен. Создаёте мультимодульный проект - один модуль: webapp, второй: jdbctemplate.

**Comment by coursar** [comment]
Либо можно обойтись вообще без модулей и просто jdbctemplate закинуть в текущий проект
