### ISSUE TITLE
Не разворачивается на хероку 

### ISSUE THREAD

**Issue by AleksandrNagovitsyn** [AleksandrNagovitsyn/TXTSearch#3]
@coursar 
https://txtsearch.herokuapp.com/
![image](https://user-images.githubusercontent.com/55318485/71114336-9d14d300-21e0-11ea-925e-48a142b94514.png)

При разворачивании на хероку эксепшены лезут, в трэвисе при этом все собирается, проблем нет. 
Хероку, судя по всему, не может найти подключение к БД. 
Вероятнее всего, у меня проблемы в Procfile, но я сделал 20 разных коммитов с разными вариантами Procfile, и ни один не сработал

**Comment by coursar** [comment]
Должно быть ` --enable-naming`. И нужно убрать мусор из репо.

Нужно читать Exception'ы. Вам чётко написано, что NPE в JdbcTemplate.java:15 и дальше по списку.
